### ISSUE TITLE
Build dev failed: no such file or directory \node_modules\@ionic\storage\dist\es5

### ISSUE THREAD

**Issue by kashban** [driftyco/ionic-storage#17]
I uninstalled and reinstalled @ionic/storage with --save on my project but ever since get this error message when running `ionic serve`:

```
[11:22:47]  Error: Could not resolve entry (./.tmp/app/main.dev.js)
    at C:\Daten\Entwicklung\e-netz\PROMT-UI_V2\node_modules\rollup\dist\rollup.js:8602:28
    at process._tickCallback (internal/process/next_tick.js:103:7)

[11:22:47]  sass started ...
[11:22:47]  build dev failed:  Build failed: ENOENT: no such file or directory, scandir 'c:\Daten\Entwicklung\e-netz\PROMT-UI_V2\node_modules\@ionic\storage\dist\es5'

[11:22:47]  Error: ENOENT: no such file or directory, scandir 'c:\Daten\Entwicklung\e-netz\PROMT-UI_V2\node_modules\@ionic\storage\dist\es5'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at getSiblingSassFiles (C:\Daten\Entwicklung\e-netz\PROMT-UI_V2\node_modules\@ionic\app-scripts\dist\sass.js:126:17)
    at addComponentSassFiles (C:\Daten\Entwicklung\e-netz\PROMT-UI_V2\node_modules\@ionic\app-scripts\dist\sass.js:100:24)
    at C:\Daten\Entwicklung\e-netz\PROMT-UI_V2\node_modules\@ionic\app-scripts\dist\sass.js:95:9
    at Array.forEach (native)
    at getComponentSassFiles (C:\Daten\Entwicklung\e-netz\PROMT-UI_V2\node_modules\@ionic\app-scripts\dist\sass.js:94:26)
    at generateSassData (C:\Daten\Entwicklung\e-netz\PROMT-UI_V2\node_modules\@ionic\app-scripts\dist\sass.js:79:30)
    at Object.sass (C:\Daten\Entwicklung\e-netz\PROMT-UI_V2\node_modules\@ionic\app-scripts\dist\sass.js:38:9)
    at C:\Daten\Entwicklung\e-netz\PROMT-UI_V2\node_modules\@ionic\app-scripts\dist\build.js:63:23
```

Looking at the node_modules/@ionic/storage directory the error message is correct: There is no "dist" directory, only es5 and es2015. 

My package.json:

```
{
  "dependencies": {
    "@ionic/storage": "^1.1.2",
    "ag-grid": "^6.0.1",
    "ag-grid-enterprise": "^6.0.1",
    "angular-2-local-storage": "0.0.19",
    "electron-squirrel-startup": "^1.0.0",
    "ionic-angular": "^2.0.0-rc.0",
    "ionic-native": "^2.0.3",
    "ionicons": "^3.0.0",
    "keycloak": "^1.2.0",
    "ng2-resource-rest": "^1.4.0",
    "reflect-metadata": "0.1.8"
  },
  "devDependencies": {
    "@ionic/app-scripts": "^0.0.23",
    "tslint-ionic-rules": "0.0.5",
    "typescript": "^2.0.3"
  },
  "name": "promtui",
  "description": "Promt-UI: An Ionic 2 project",
  "version": "1.0.0",
  "author": "Juergen Wahlmann",
  "build": {
    "appId": "promt-ui",
    "category": "demo",
    "win": {
      "iconUrl": "http://resources/icon.ico",
      "msi": true
    },
    "asar": false
  },
  "directories": {
    "app": "dist/desktop/www"
  },
  "cordovaPlugins": [
    "cordova-plugin-device",
    "cordova-plugin-console",
    "cordova-plugin-whitelist",
    "cordova-plugin-splashscreen",
    "cordova-plugin-statusbar",
    "ionic-plugin-keyboard"
  ],
  "cordovaPlatforms": [],
  "scripts": {
    "electron": "electron dist/desktop/build/windows/resources/app",
    "electron dist": "electron dist/desktop/build/windows/resources/app",
    "build1": "electron-packager dist/desktop/build/windows/resources/app PROMT-UI  --ignore=node_modules/* --platform=win32 --arch=all",
    "pack": "build --dir",
    "dist": "build",
    "build": "ionic-app-scripts build",
    "watch": "ionic-app-scripts watch",
    "serve:before": "watch",
    "emulate:before": "build",
    "deploy:before": "build",
    "build:before": "build",
    "run:before": "build"
  },
  "engines": {
    "node": ">= 6.6.0",
    "npm": ">= 3"
  },
  "config": {
    "ghooks": {
      "pre-commit": "npm run lint && npm run scss-lint",
      "pre-push": "npm test",
      "commit-msg": "validate-commit-msg"
    },
    "commitizen": {
      "path": "./node_modules/cz-conventional-changelog"
    }
  }
}
```

Also, if I uninstall @ionic/storage to solely use angular-2-local-storage it still references this missing directory. I could not find that reference anywhere in my project.

Any ideas how to solve this?

**Comment by mhartington** [comment]
can you provide the output from 

```
npm -v
node -v
```

**Comment by kashban** [comment]
npm -v : 3.10.8
node -v v6.9.1

I just returned to this project after some weeks of working on something else and am using CoolStorage for now since I don't concur with ion-storage to be async.

**Comment by NoNameProvided** [comment]
In the npm package the es5 version is under the `node_modules\@ionic\storage\es5` path but you were trying to import it from `node_modules\@ionic\storage\dist\es5`. So instead of 

```typescript
import { Storage } from '@ionic/storage/dist/es5';
```

you have to write:

```typescript
import { Storage } from '@ionic/storage/es5';
```

**Comment by mlynch** [comment]
Curious, what's the reason you're importing the ES5 version inside of an ES6+ context?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
