### ISSUE TITLE
Cannot read property 'substr' of undefined

### ISSUE THREAD

**Issue by speedfl** [driftyco/ionic-storage#81]
I know that it is not on your side but I am trying to use your ionic-storage

However when doing ionic serve I am getting this error

```
[17:06:52]  copy finished in 6.13 s
d:\xx\application\xxx\node_modules\webpack-sources\node_modules\source-map\lib\source-node.js:95
          var code = nextLine.substr(0, mapping.generatedColumn -
                             ^

TypeError: Cannot read property 'substr' of undefined
    at Function.<anonymous> (d:\xx\application\xxx\node_modules\webpack-sources\node_modules\source-map\lib\source-node.js:95:30)
    at Array.forEach (native)
    at SourceMapConsumer_eachMapping [as eachMapping] (d:\xx\application\xxx\node_modules\webpack-sources\node_modules\source-map\lib\source-map-consumer.js:155:14)
    at Function.SourceNode_fromStringWithSourceMap [as fromStringWithSourceMap] (d:\xx\application\xxx\node_modules\webpack-sources\node_modules\source-map\lib\source-node.js:80:24)
    at SourceMapSource.node (d:\xx\application\xxx\node_modules\webpack-sources\lib\SourceMapSource.js:42:20)
    at ReplaceSource.node (d:\xx\application\xxx\node_modules\webpack-sources\lib\ReplaceSource.js:69:29)
    at CachedSource.node (d:\xx\application\xxx\node_modules\webpack-sources\lib\CachedSource.js:12:23)
    at d:\xx\application\xxx\node_modules\webpack-sources\lib\ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (d:\xx\application\xxx\node_modules\webpack-sources\lib\ConcatSource.js:39:60)
```

I do not have this issue when I am not using it (I was on pouchDB).

here is the content of my dependencies/dev dependencies

```
"dependencies": {
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/compiler-cli": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "2.2.1",
    "@angular/http": "2.2.1",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/platform-server": "2.2.1",
    "@ionic/storage": "2.0.0",
    "@types/cropperjs": "0.0.22",
    "cropperjs": "^1.0.0-alpha",
    "ionic-angular": "2.1.0",
    "ionic-native": "2.8.0",
    "ionicons": "3.0.0",
    "ng2-translate": "^5.0.0",
    "ng2-ui-auth": "^6.0.0",
    "qrcode-generator": "^1.0.7",
    "rxjs": "5.0.0-beta.12",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.6.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.1.4",
    "rollup-plugin-commonjs": "^6.0.0",
    "typescript": "2.0.9"
  },
```

I just would like to know if there is a way to bypass this issue

Best regards

**Comment by NoNameProvided** [comment]
Looking at the stack this is most likely related to your build tool (you use ionic-app-scripts probably). It seems it cannot generate the sourcemap for some reason. Its better if you are opening an issue [there](https://github.com/driftyco/ionic-app-scripts/issues/new).

**Comment by speedfl** [comment]
I understand but what is strange is that I do not have this issue when I am not using ionic-storage... Weird...

**Comment by speedfl** [comment]
You can close the issue if you want. It fact it was due to my custom rollup config
